# Generated by Django 6.0.2 on 2026-03-04 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_seed_plans_and_agebands'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProductAgeBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('age_band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_product_age_bands', to='products.ageband')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_product_age_bands', to='products.company')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_product_age_bands', to='products.product')),
            ],
            options={
                'ordering': ['company', 'product', 'age_band'],
                'unique_together': {('company', 'product', 'age_band')},
            },
        ),
        migrations.CreateModel(
            name='CompanyProductPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_product_plans', to='products.company')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_product_plans', to='products.plan')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_product_plans', to='products.product')),
            ],
            options={
                'ordering': ['company', 'product', 'plan'],
                'unique_together': {('company', 'product', 'plan')},
            },
        ),
    ]
