# Generated by Django 6.0.2 on 2026-03-04 20:22

from django.db import migrations, models


def _migrate_rates_to_columns(apps, schema_editor):
    ProductPrice = apps.get_model('products', 'ProductPrice')

    for row in ProductPrice.objects.all().iterator():
        if row.gender == 'M':
            row.male_rate = row.rate
        elif row.gender == 'F':
            row.female_rate = row.rate
        else:
            if row.male_rate is None:
                row.male_rate = row.rate
            if row.female_rate is None:
                row.female_rate = row.rate
        row.save(update_fields=['male_rate', 'female_rate'])

    grouped = {}
    for row in ProductPrice.objects.all().order_by('id').iterator():
        key = (row.company_id, row.product_id, row.plan_id, row.age_band_id)
        grouped.setdefault(key, []).append(row)

    for rows in grouped.values():
        keeper = rows[0]
        male_rate = keeper.male_rate
        female_rate = keeper.female_rate
        for row in rows[1:]:
            if male_rate is None and row.male_rate is not None:
                male_rate = row.male_rate
            if female_rate is None and row.female_rate is not None:
                female_rate = row.female_rate
        keeper.male_rate = male_rate
        keeper.female_rate = female_rate
        keeper.save(update_fields=['male_rate', 'female_rate'])
        ProductPrice.objects.filter(id__in=[r.id for r in rows[1:]]).delete()


def _noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('products', '0003_companyproductageband_companyproductplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprice',
            name='female_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='productprice',
            name='male_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.RunPython(_migrate_rates_to_columns, _noop_reverse),
        migrations.AlterUniqueTogether(
            name='productprice',
            unique_together={('company', 'product', 'plan', 'age_band')},
        ),
        migrations.AlterModelOptions(
            name='productprice',
            options={'ordering': ['company', 'product', 'plan', 'age_band']},
        ),
        migrations.RemoveField(
            model_name='productprice',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='productprice',
            name='rate',
        ),
    ]
